services:
#    scorekeeper.example:
#        class: ScorekeeperBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    security.access.account_voter:
        class:      ScorekeeperBundle\Security\Authorization\Voter\AccountVoter
        public:     false
        tags:
           - { name: security.voter }