<?php

namespace ScorekeeperBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultRepository extends EntityRepository {

    public function findByLeagueUser($league_id, $user_id) {
        //select * from Result 
        //left join User on Result.user_id=User.id 
        //left join Contest on Result.contest_id=Contest.id 
        //where user_id=3 and league_id=1 order by date;
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT r,c 
                                    FROM ScorekeeperBundle:Result r
                                JOIN r.contest c
                                WHERE c.league=:league_id
                                AND r.user=:user_id
                                ORDER BY c.date'
                        )
                        ->setParameters(array('league_id' => $league_id, 'user_id' => $user_id))
                        ->getResult();
    }

}
